### ISSUE TITLE
Repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by Aoshee** [fffaraz/dockerweb#3]
Hello,
I run command: docweb build:all but error:
`checking for libzip... not found
configure: error: Please reinstall the libzip distribution
The command '/bin/sh -c chown root:root /script_.sh && chmod 540 /script_.sh && sync && /script_init.sh' returned a non-zero code: 1

/opt/dockerweb/docweb build app/phpmyadmin
Sending build context to Docker daemon 12.29kB
Step 1/3 : FROM fffaraz/web/php7nginx:latest
pull access denied for fffaraz/web/php7nginx, repository does not exist or may require 'docker login'
echo DONE
DONE
exit 0
`
I already install libzip-dev. I run in Ubuntu 16.04 LTS.

**Comment by fffaraz** [comment]
I guess it should be fixed now.

**Comment by bportman** [comment]
Same issue running `docweb proxy:run` - says fffaraz/proxy:latest does not exist or ay require docker login.  Just installed dockerweb today on clean Ubuntu 18.x LTS image.

**Comment by fffaraz** [comment]
Did you run `docweb build:all` ?

**Comment by bportman** [comment]
Yes, the first time I ran it my SSH session timed out so I ran it again and it finished.  I ran it a 3rd time not just to see and I still get the same error. There's a lot of output from `docweb build:all` - could it be something failed and I missed it?  I guess I can create a log file and check it.

**Comment by Aoshee** [comment]
docker: Error response from daemon: pull access denied for fffaraz/proxy, repository does not exist or may require 'docker login'.
docker: Error response from daemon: pull access denied for fffaraz/app/mysqltuner, repository does not exist or may require 'docker login'
Please open docker hub?
